  version: '3.8'
  
  services:
    consul-server:
      image: consul:1.15
      ports:
        - "8500:8500"
      command: "agent -server -ui -node=consul-server -bootstrap-expect=1 -client=0.0.0.0"
      environment:
        - CONSUL_BIND_INTERFACE=eth0
    api-gateway:
      build: ./api-gateway
      ports:
          - "8000:8000"
      depends_on:
          - task-service
          - project-service
          - communication-service
          - report-service
          - schedule-service
          - consul-server
      environment:
          - CONSUL_HOST=consul-server
          - SERVICE_NAME=api-gateway
          - SERVICE_PORT=8000

    project-service:
      build: ./project-service
      ports:
        - "8002:8002"
      depends_on:
        - consul-server
        - project-db
      environment:
        - CONSUL_HOST=consul-server
        - SERVICE_NAME=project-service
        - SERVICE_PORT=8002

    task-service:
      build: ./task-service
      ports:
        - "8001:8001"
      depends_on:
        - consul-server
        - task-db
      environment:
        - CONSUL_HOST=consul-server
        - SERVICE_NAME=task-service
        - SERVICE_PORT=8001
  ## ====test=====
#    task-service-2:
#      build: ./task-service
#      ports:
#        - "8006:8001"
#      depends_on:
#        - consul-server
#        - task-db
#      environment:
#        - CONSUL_HOST=consul-server
#        - SERVICE_NAME=task-service
#        - SERVICE_PORT=8001
  ## =============
    communication-service:
      build: ./communication-service
      ports:
        - "8005:8005"
  
    report-service:
      build: ./report-service
      ports:
        - "8003:8003"
  
    schedule-service:
      build: ./schedule-service
      ports:
        - "8004:8004"
  
    task-db:
      image: postgres:15
      environment:
        POSTGRES_DB: taskdb
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
      volumes:
        - task-db-data:/var/lib/postgresql/data
    project-db:
      image: postgres:15
      environment:
        POSTGRES_DB: projectdb
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        - "5433:5432"  # 5433 zewnętrzny, 5432 wewnątrz kontenera
      volumes:
        - project-db-data:/var/lib/postgresql/data
  volumes:
    task-db-data:
    project-db-data:
  
