version: '3.8'

services:
  project-service:
    build: ./project-service
    ports:
      - "8000:8000"

  task-service:
    build: ./task-service
    ports:
      - "8001:8001"

  communication-service:
    build: ./communication-service
    ports:
      - "8002:8002"

  report-service:
    build: ./report-service
    ports:
      - "8003:8003"

  schedule-service:
    build: ./schedule-service
    ports:
      - "8004:8004"
